# Generated by Django 4.2 on 2026-01-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='careplan',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
