# Generated by Django 4.2 on 2026-02-11 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_careplan_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mrn', models.CharField(max_length=6, unique=True)),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('npi', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='careplan',
            name='additional_diagnosis',
        ),
        migrations.RemoveField(
            model_name='careplan',
            name='clinical_notes',
        ),
        migrations.RemoveField(
            model_name='careplan',
            name='medication_history',
        ),
        migrations.RemoveField(
            model_name='careplan',
            name='medication_name',
        ),
        migrations.RemoveField(
            model_name='careplan',
            name='patient_dob',
        ),
        migrations.RemoveField(
            model_name='careplan',
            name='patient_first_name',
        ),
        migrations.RemoveField(
            model_name='careplan',
            name='patient_last_name',
        ),
        migrations.RemoveField(
            model_name='careplan',
            name='patient_mrn',
        ),
        migrations.RemoveField(
            model_name='careplan',
            name='patient_primary_diagnosis',
        ),
        migrations.RemoveField(
            model_name='careplan',
            name='referring_provider',
        ),
        migrations.RemoveField(
            model_name='careplan',
            name='referring_provider_npi',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=200)),
                ('primary_diagnosis', models.CharField(max_length=20)),
                ('additional_diagnosis', models.TextField(blank=True)),
                ('medication_history', models.TextField(blank=True)),
                ('clinical_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='app.patient')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='app.provider')),
            ],
        ),
        migrations.AddField(
            model_name='careplan',
            name='order',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='care_plan', to='app.order'),
            preserve_default=False,
        ),
    ]
